config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "searches#index"

  resources :search_histories
  resources :searches do
    member do
      get :sidebar
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord

  before_save :update_total
  validates_presence_of :keyword
  validates_uniqueness_of :keyword
  
  VALID_SORT_ORDERS = ['created_at desc', 'create_date asc', 'keyword desc', 'keyword asc', 'total desc', 'total asc']
                        
  def self.top_10_game_searches
    self.order('total desc').first(10)
  end
  
  def self.create_or_update_total(keyword)
    search_history = SearchHistory.where("keyword" => keyword).first
    if search_history.blank?
      search_history = self.create(keyword: keyword,
                                   total: 0)
    else
      search_history.save
    end
    search_history
  end

  def self.sort_by(order)
    if VALID_SORT_ORDERS.include?(order)
      self.order(order)
    else
      self
    end
    
  end
  
  private

  def update_total
    if self.total.blank?
      self.total = 1
    else
      self.total = self.total + 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController

  def index
    @search_histories = SearchHistory.sort_by(params[:sort]).paginate(page: params.fetch(:page, 1))
    @hide_sidebar=true
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end

  def create
    if IGDB_CONNECTION.nil?
      Rails.logger.warn("IGDB connection not established")
    else
      @search_history = SearchHistory.create_or_update_total(params[:query])
      @results = IGDB_CONNECTION::Game.search(query: params[:query])
    end
  end

  def sidebar
    if IGDB_CONNECTION.nil?
      Rails.logger.warn("IGDB connection not established")
    else
      @results = IGDB_CONNECTION::Game.search(query: params[:id])
    end
    render :create
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_sidebar.html.erb
<% unless @hide_sidebar %>
  <div class='item header'>
    <h2>Top Searches</h2>
    <strong><%= link_to 'View all searches', search_histories_path %></strong>
  </div>
  <% SearchHistory.top_10_game_searches.each do |search| %>
    <%= link_to "#{search.keyword.to_s.truncate(40)} #{search.total}", sidebar_search_path(search.keyword), class: 'item', remote: true %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameArch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <body>
    <div class="ui sidebar inverted visible vertical menu">
      <div id='sidebar'>
	<%= render partial: 'layouts/sidebar' %>
      </div>
    </div>
    <div class="pusher">
      <div class="ui main text container">
	<br />
	<%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/search_histories/index.html.erb
<h1 class="ui header">Game Arch: Search histories</h1>

<%= will_paginate @search_histories %>
<%= link_to 'Go back', root_path %>
<table>
  <thead>
    <th>Keyword 
      <%= link_to 'a-z', search_histories_path(sort: 'keyword asc', page: params[:page]) %>
      <%= link_to 'z-a', search_histories_path(sort: 'keyword desc', page: params[:page]) %> 
    </th>
    <th>
      Count
      <%= link_to 'most', search_histories_path(sort: 'total desc', page: params[:page]) %>
      <%= link_to 'least', search_histories_path(sort: 'total asc', page: params[:page]) %> 
    </th>
    <th>
      Date
      <%= link_to 'new', search_histories_path(sort: 'created_at desc', page: params[:page]) %>
      <%= link_to 'old', search_histories_path(sort: 'created_at asc', page: params[:page]) %> 
    </th>
  </thead>
  <tbody>
    <% @search_histories.each do |search_history| %>
      <tr>
	<td><%= search_history.keyword.to_s.truncate(40) %></td>
	<td><%= search_history.total %></td>
	<td><%= search_history.created_at %></td>	
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @search_histories %>

app/views/searches/_results.html.erb
<% if @results.blank? %>
  There were no results. 
<% else %>
<% unless @search_history.blank? %>
  <em>This search has been performed <%= @search_history.total %> <%= 'time'.pluralize(@search_history.total) %></em>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |result| %>
      <tr>
	<% if result.alternative_names.blank? %>
          <td>none</td>
	<% else %>
	  <td><%= result.alternative_names.collect{|each| each['name']}.join(' ') %></td>
	<% end %>
	<td><%= result.summary.to_s.truncate(300) %></td>
	<% if result.rating_count.to_i < 1 %>
	   <td>no votes</td>
        <% else %>
  	   <td><%= result.rating.to_s.first(2) %>% of <%= result.rating_count %> votes</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/searches/index.html.erb
<h1 class="ui header">Game Arch</h1>
<p>Please enter a keyword to search, for example 'batman'.</p>

<div class="ui action left icon input">
  <%= form_tag searches_path, remote: true do %>  
    <i class="search icon"></i>
    <%= text_field_tag :query, params[:query], placeholder: "Search..." %>
    <%= submit_tag :search, class: "ui grey button" %>
  <% end %>
</div>

<div id='results'></div>